import re
from collections import defaultdict
from datetime import datetime, timezone

import yaml

from const import (
    ACTIONS_URL, CATEGORIES, CLOCK_ICON, CONTACT_EMAIL, DATA_FILE,
    FALLBACK_CATEGORY, MONTH_ABBREVIATIONS, README_FILE, STAR_ICON,
    STARS_URL, TAG_ICON,
)


def humanize_count(count):
    count = int(count or 0)
    if count >= 1000:
        return f"{count / 1000:.1f}".rstrip("0").rstrip(".") + "k"
    return str(count)


def slugify(text):
    kept = "".join(char for char in text.lower() if char.isalnum() or char in " -")
    return kept.replace(" ", "-")


SYNC_BANNER_RE = re.compile(r"^# Generated by scripts/sync\.py on (.+)$", re.MULTILINE)


def sync_timestamp(raw):
    match = SYNC_BANNER_RE.match(raw)
    if not match:
        return None
    try:
        return datetime.strptime(match.group(1), "%Y-%m-%d %H:%M UTC").replace(tzinfo=timezone.utc)
    except ValueError:
        return None


def format_date(value):
    if not value:
        return ""
    if hasattr(value, "strftime"):
        date = value
    else:
        try:
            date = datetime.strptime(str(value), "%Y-%m-%d")
        except ValueError:
            return str(value)
    return f"{MONTH_ABBREVIATIONS[date.month]} {date.day}, {date.year}"


def render_entry(entry):
    name = entry["repo"]
    url = entry.get("url") or f"https://github.com/{name}"
    description = (entry.get("description") or "").strip()
    tags = " ".join(f"`{tag}`" for tag in (entry.get("tags") or [])[:3])
    starred_at = entry.get("starred_at", "")
    meta = " ".join(filter(None, [
        f"{TAG_ICON} {tags}" if tags else "",
        f"{STAR_ICON} {humanize_count(entry.get('stars'))} stars",
        f"{CLOCK_ICON} starred {format_date(starred_at)}" if starred_at else "",
    ]))

    lines = [f"**[{name}]({url})**"]
    if meta:
        lines.append(meta)
    if description:
        lines.append(description)
    return "  \n".join(lines)


def render(entries, synced_at=None):
    grouped = defaultdict(list)
    for entry in entries:
        grouped[entry.get("category") or FALLBACK_CATEGORY].append(entry)

    ordered_categories = [c for c in CATEGORIES if c in grouped]
    ordered_categories += sorted(c for c in grouped if c not in CATEGORIES)

    rounded_total = len(entries) // 5 * 5
    synced_on = format_date(synced_at or datetime.now(timezone.utc))
    contents = "\n".join(
        f"- [{category}](#{slugify(category)}) ({len(grouped[category])})"
        for category in ordered_categories
    )

    sections = [
        "# github-stars",
        "",
        f"This repo is an automatically maintained catalog of the {rounded_total}+ "
        f"repositories I've [starred on GitHub]({STARS_URL}). A weekly "
        f"[GitHub Actions workflow]({ACTIONS_URL}) pulls my current stars from the GitHub "
        "API, classifies each repo into one of a fixed set of categories, and writes a "
        "short description and a few tags for it. The results get committed back here and "
        "rendered into the README below.",
        "",
        "Suggestions and project recommendations are welcome at "
        f"[{CONTACT_EMAIL}](mailto:{CONTACT_EMAIL}).",
        "",
        f"_Last synced {synced_on}_",
        "",
        "## Contents",
        "",
        contents,
        "",
    ]
    for category in ordered_categories:
        repos = sorted(
            grouped[category],
            key=lambda entry: (-int(entry.get("stars") or 0), entry["repo"].lower()),
        )
        sections.append(f"## {category}")
        sections.append("")
        for entry in repos:
            sections.append(render_entry(entry))
            sections.append("")

    return "\n".join(sections).rstrip() + "\n"


def main():
    if not DATA_FILE.exists():
        raise SystemExit(f"Data file not found: {DATA_FILE}. Run scripts/sync.py first.")
    raw = DATA_FILE.read_text(encoding="utf-8")
    entries = yaml.safe_load(raw) or []
    README_FILE.write_text(render(entries, sync_timestamp(raw)), encoding="utf-8")
    categories = {entry.get("category") for entry in entries}
    print(f"README.md: {len(entries)} repositories across {len(categories)} categories")


if __name__ == "__main__":
    main()
