import json
import os
import sys
import time
from datetime import datetime, timezone

import requests
import yaml
from cursor_sdk import Agent, AgentOptions, CloudAgentOptions, CursorAgentError
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

from const import (
    BATCH_SIZE, CATEGORIES, DATA_FILE, FALLBACK_CATEGORY, MODEL, PROMPT, TAGS,
    TAGS_PER_REPO, USER,
)

RETRYABLE_STATUS = [429, 502, 503, 504]
GENERATED_BANNER = "# Generated by scripts/sync.py on {timestamp}\n\n"
TAG_SET = set(TAGS)
DESCRIPTION_LIMIT = 140


def github_session(token):
    session = requests.Session()
    session.headers.update({
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github.star+json",
        "X-GitHub-Api-Version": "2022-11-28",
    })
    retries = Retry(
        total=4,
        backoff_factor=1.5,
        status_forcelist=RETRYABLE_STATUS,
        respect_retry_after_header=True,
    )
    session.mount("https://", HTTPAdapter(max_retries=retries))
    return session


def fetch_stars(user, token):
    session = github_session(token)
    url = f"https://api.github.com/users/{user}/starred"
    stars = []
    page = 1
    while True:
        response = session.get(url, params={"per_page": 100, "page": page}, timeout=30)
        response.raise_for_status()
        batch = response.json()
        if not batch:
            break
        for item in batch:
            repo = item["repo"]
            stars.append({
                "repo": repo["full_name"],
                "url": repo["html_url"],
                "about": repo.get("description") or "",
                "topics": repo.get("topics", []),
                "language": repo.get("language") or "",
                "stars": repo.get("stargazers_count", 0),
                "starred_at": item["starred_at"][:10],
            })
        if int(response.headers.get("X-RateLimit-Remaining", 1)) < 5:
            reset_at = int(response.headers.get("X-RateLimit-Reset", 0))
            time.sleep(max(0, reset_at - time.time()) + 5)
        page += 1
    return stars


def parse_json_array(text):
    start = text.find("[")
    end = text.rfind("]")
    if start == -1 or end <= start:
        raise json.JSONDecodeError("no JSON array found", text, 0)
    return json.loads(text[start:end + 1])


def clean_description(text, limit=DESCRIPTION_LIMIT):
    text = (text or "").strip()
    if len(text) <= limit:
        return text
    return text[:limit].rsplit(" ", 1)[0].rstrip(".,;:- ") + "…"


def clean_tags(tags):
    cleaned = []
    for tag in tags or []:
        tag = str(tag).strip().lower().replace(" ", "-")
        if tag in TAG_SET and tag not in cleaned:
            cleaned.append(tag)
    return cleaned[:TAGS_PER_REPO]


def agent_options():
    return AgentOptions(
        api_key=os.environ["CURSOR_API_KEY"],
        model=MODEL,
        cloud=CloudAgentOptions(repos=[]),
    )


def categorize_batch(repos):
    listing = "\n\n".join(
        f"Repo: {repo['repo']}\nAbout: {repo['about']}\nLanguage: {repo['language']}\n"
        f"Topics: {', '.join(repo['topics']) or 'none'}"
        for repo in repos
    )
    try:
        result = Agent.prompt(f"{PROMPT}\n\n{listing}", agent_options())
        if result.status == "error":
            raise ValueError(f"run failed: {result.id}")
        return parse_json_array(result.result or "")
    except (json.JSONDecodeError, ValueError, CursorAgentError, KeyError, IndexError):
        if len(repos) > 1:
            mid = len(repos) // 2
            return categorize_batch(repos[:mid]) + categorize_batch(repos[mid:])
        return []


def categorize(repos):
    classified = {}
    for start in range(0, len(repos), BATCH_SIZE):
        batch = repos[start:start + BATCH_SIZE]
        print(f"Categorizing {start + 1}-{start + len(batch)} of {len(repos)}")
        for item in categorize_batch(batch):
            name = item.get("repo")
            if not name:
                continue
            category = item.get("category")
            classified[name] = {
                "description": clean_description(item.get("description")),
                "category": category if category in CATEGORIES else FALLBACK_CATEGORY,
                "tags": clean_tags(item.get("tags")),
            }
    for repo in repos:
        classified.setdefault(repo["repo"], {
            "description": repo["about"],
            "category": FALLBACK_CATEGORY,
            "tags": [repo["language"].lower()] if repo["language"].lower() in TAG_SET else [],
        })
    return classified


def load_existing(path):
    if not path.exists():
        return {}
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or []
    return {entry["repo"]: entry for entry in data}


def needs_categorization(repo, existing):
    entry = existing.get(repo)
    return entry is None or entry.get("category") not in CATEGORIES


def merge(existing, stars, classified):
    entries = []
    for star in stars:
        previous = existing.get(star["repo"], {})
        meta = classified.get(star["repo"]) or previous
        entries.append({
            "repo": star["repo"],
            "url": star["url"],
            "description": meta.get("description") or star["about"],
            "category": meta.get("category") or FALLBACK_CATEGORY,
            "tags": meta.get("tags") or [],
            "stars": star["stars"],
            "starred_at": star["starred_at"],
        })
    entries.sort(key=lambda entry: (
        entry["category"], -int(entry.get("stars") or 0), entry["repo"].lower()
    ))
    return entries


def save(path, entries):
    path.parent.mkdir(parents=True, exist_ok=True)
    timestamp = f"{datetime.now(timezone.utc):%Y-%m-%d %H:%M UTC}"
    temp_path = path.parent / (path.name + ".tmp")
    with temp_path.open("w", encoding="utf-8") as file:
        file.write(GENERATED_BANNER.format(timestamp=timestamp))
        yaml.safe_dump(
            entries,
            file,
            sort_keys=False,
            allow_unicode=True,
            default_flow_style=False,
            width=120,
        )
    os.replace(temp_path, path)


def main():
    token = os.environ["GITHUB_TOKEN"]
    retag_all = "--retag-all" in sys.argv

    stars = fetch_stars(USER, token)
    print(f"Fetched {len(stars)} starred repos")

    existing = load_existing(DATA_FILE)
    if retag_all:
        pending = stars
        print("--retag-all set: re-tagging every starred repo")
    else:
        pending = [star for star in stars if needs_categorization(star["repo"], existing)]
    print(f"{len(pending)} repos need categorization")

    classified = categorize(pending) if pending else {}
    entries = merge(existing, stars, classified)
    save(DATA_FILE, entries)
    print(f"Wrote {len(entries)} entries to {DATA_FILE}")


if __name__ == "__main__":
    main()
